function [fitresult, gof] = fit_trans_v_0(v_0_interest, num_transitions_interest)
%CREATEFIT(V_0_INTEREST,NUM_TRANSITIONS_INTEREST)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : v_0_interest
%      Y Output: num_transitions_interest
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 27-Nov-2020 13:23:46


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( v_0_interest, num_transitions_interest );

% Set up fittype and options.
ft = fittype( 'a*exp(-b*(x-5)^2)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.157613081677548 0.970592781760616];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'num_transitions_interest vs. v_0_interest', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'v_0_interest', 'Interpreter', 'none' );
ylabel( 'num_transitions_interest', 'Interpreter', 'none' );
grid on


