function [fitresult, gof] = fit_trans_delta_t_norm(omega_delta_t_interest, num_transitions_interest)
%CREATEFIT(OMEGA_DELTA_T_INTEREST,NUM_TRANSITIONS_INTEREST)
%  Create a fit.
%
%  Data for 'untitled fit 2' fit:
%      X Input : omega_delta_t_interest
%      Y Output: num_transitions_interest
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 27-Nov-2020 15:59:28


%% Fit: 'untitled fit 2'.
[xData, yData] = prepareCurveData( omega_delta_t_interest, num_transitions_interest );

% Set up fittype and options.
ft = fittype( 'a*exp(-b*(x-1)^2)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.469262098702482 0.478708973212856];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'untitled fit 2' );
h = plot( fitresult, xData, yData );
legend( h, 'num_transitions_interest vs. omega_delta_t_interest', 'untitled fit 2', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'omega_delta_t_interest', 'Interpreter', 'none' );
ylabel( 'num_transitions_interest', 'Interpreter', 'none' );
grid on


