function [fitresult, gof] = fit_curve_trans(delta_t_interest, num_transitions_interest,v_0,R,D)
%CREATEFIT(DELTA_T_INTEREST,NUM_TRANSITIONS_INTEREST)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : delta_t_interest
%      Y Output: num_transitions_interest
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 26-Nov-2020 15:56:39


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( delta_t_interest, num_transitions_interest );

% Set up fittype and options.
ft = fittype( 'a*exp(-1.5*b*(0.5*x-1)^2./x)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.0318328463774207 0.27692298496089];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'num_transitions_interest vs. delta_t_interest', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'delta_t_interest', 'Interpreter', 'none' );
ylabel( 'num_transitions_interest', 'Interpreter', 'none' );
grid on